export const icons = {
    typescript: "/icons/typescript.webp",
    react: "/icons/react.webp",
    angular: "/icons/angular.webp",
    next: "/icons/nextjs.webp",
    nest: "/icons/nest.ico",
    vue: "/icons/vue.webp",
    tailwind: "/icons/tailwind.webp",
    postgres: "/icons/postgres.png",
    flutter: "/icons/flutter.webp",
    firebase: "/icons/firebase.webp",
    python: "/icons/python.webp",
    threejs: "/icons/threejs.webp",
    figma: "/icons/figma.webp",
    node: "/icons/node.webp",
    docker: "/icons/docker.webp",
    github: "/icons/github.webp",
    linkedin: "/icons/linkedIn.webp",
    shutdown: "/icons/power.webp",
}
